default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: progress_test_development

test:
  <<: *default
  database: progress_test_test

production:
  <<: *default
  database: progress_test_production
  username: progress_test
  password: <%= ENV['PROGRESS_TEST_DATABASE_PASSWORD'] %>
